export type PresetTransaction = {
  description: string;
  type: "expense" | "income";
  category: string;
  minAmount: number;
  maxAmount: number;
  fixedAmounts?: number[];
  isCustom?: boolean;
};

export const TRANSACTION_CATEGORIES = [
  "Spesa e supermercati",
  "Generi alimentari e supermercato",
  "Ristorazione e bar",
  "Ristoranti e bar",
  "Trasporti",
  "Carburanti",
  "Casa",
  "Prelievi",
  "Bonifici ricevuti",
  "Altre uscite",
  "Salute e benessere",
  "Tempo libero",
  "Tabaccai e simili",
  "Tasse e bolli",
  "Trasferimenti",
  "Sanità",
  "Trasporti e viaggi",
  "Servizi",
];

export const DEFAULT_PRESETS: PresetTransaction[] = [
  { description: "Bonifico Disposto Da CAMMAROTA DONATO C. S.N.C.", type: "income", category: "Bonifici ricevuti", minAmount: 300, maxAmount: 600 },
  { description: "Bonifico Disposto Da INPS", type: "income", category: "Bonifici ricevuti", minAmount: 30, maxAmount: 650 },
  { description: "Bonifico Istantaneo Disposto Da LAURENZIELLO GIOVINA", type: "income", category: "Bonifici ricevuti", minAmount: 15, maxAmount: 200 },
  { description: "Bonifico Istantaneo Disposto Da A.P.S.E.M. CLUB PUNTO SPORT CAFFE'", type: "income", category: "Bonifici ricevuti", minAmount: 50, maxAmount: 100 },
  { description: "Bonifico Disposto Da Mangopay", type: "income", category: "Bonifici ricevuti", minAmount: 30, maxAmount: 50 },
  { description: "Bonifico Disposto Da Gbo Italy SpA", type: "income", category: "Bonifici ricevuti", minAmount: 40, maxAmount: 60 },
  { description: "Dok Via Giosue' Carducci 32", type: "expense", category: "Generi alimentari e supermercato", minAmount: 3, maxAmount: 20 },
  { description: "Coop Superstore C.da Bosche", type: "expense", category: "Generi alimentari e supermercato", minAmount: 5, maxAmount: 20 },
  { description: "Coop Superstore Melfi", type: "expense", category: "Generi alimentari e supermercato", minAmount: 5, maxAmount: 15 },
  { description: "Pv185ep Via Foggia Melfi 85", type: "expense", category: "Generi alimentari e supermercato", minAmount: 8, maxAmount: 40 },
  { description: "Morano Srl Via Foggia", type: "expense", category: "Generi alimentari e supermercato", minAmount: 9, maxAmount: 25 },
  { description: "Penny Market S.r.l.", type: "expense", category: "Generi alimentari e supermercato", minAmount: 20, maxAmount: 130 },
  { description: "Lidl 1972", type: "expense", category: "Generi alimentari e supermercato", minAmount: 10, maxAmount: 50 },
  { description: "Md Ripacandida S.spiano Del", type: "expense", category: "Generi alimentari e supermercato", minAmount: 15, maxAmount: 35 },
  { description: "Iper Molfetta", type: "expense", category: "Generi alimentari e supermercato", minAmount: 1, maxAmount: 15 },
  { description: "Despar Largo Finlandia Bari", type: "expense", category: "Generi alimentari e supermercato", minAmount: 10, maxAmount: 20 },
  { description: "Supermercato Despar Via For", type: "expense", category: "Generi alimentari e supermercato", minAmount: 3, maxAmount: 20 },
  { description: "Al Solito Posto Via San Lor", type: "expense", category: "Tabaccai e simili", minAmount: 4, maxAmount: 10 },
  { description: "Coretti Francesco Molfetta", type: "expense", category: "Tabaccai e simili", minAmount: 3, maxAmount: 8 },
  { description: "Fama S.r.l.s. Contrada Bosc", type: "expense", category: "Ristoranti e bar", minAmount: 4, maxAmount: 10 },
  { description: "Pizzeria Del Borgo Via Colu", type: "expense", category: "Ristoranti e bar", minAmount: 8, maxAmount: 15 },
  { description: "Metro' Pizzeria Via Roma 14", type: "expense", category: "Ristoranti e bar", minAmount: 10, maxAmount: 20 },
  { description: "Red Note S.r.l.s.", type: "expense", category: "Ristoranti e bar", minAmount: 15, maxAmount: 30 },
  { description: "SumUp *Room Food Rapolla", type: "expense", category: "Ristoranti e bar", minAmount: 10, maxAmount: 40 },
  { description: "Chapeau Le Gourmet Gr Rac A", type: "expense", category: "Ristoranti e bar", minAmount: 15, maxAmount: 30 },
  { description: "Ccoffee Shop Srl Via Olive", type: "expense", category: "Ristoranti e bar", minAmount: 1, maxAmount: 8 },
  { description: "Mc Donald's C/o Centro Comm", type: "expense", category: "Ristoranti e bar", minAmount: 10, maxAmount: 30 },
  { description: "Cup&go Ss407 Basentana Potenza", type: "expense", category: "Ristoranti e bar", minAmount: 3, maxAmount: 8 },
  { description: "La Rustica Srls Strada Stat", type: "expense", category: "Ristoranti e bar", minAmount: 6, maxAmount: 15 },
  { description: "Kikyo Sushi Via Della Mecca", type: "expense", category: "Ristoranti e bar", minAmount: 25, maxAmount: 50 },
  { description: "Caffe' Del Viale Di Mo Via", type: "expense", category: "Ristoranti e bar", minAmount: 3, maxAmount: 10 },
  { description: "Maglione Pizzeriasarni Cc Gran Foggia", type: "expense", category: "Ristoranti e bar", minAmount: 2, maxAmount: 15 },
  { description: "Coil Barile Strada Statale", type: "expense", category: "Carburanti", minAmount: 10, maxAmount: 30 },
  { description: "40653 Rapolla Pz Via Barl", type: "expense", category: "Carburanti", minAmount: 10, maxAmount: 20 },
  { description: "Stazione Di Servizio F Cont", type: "expense", category: "Carburanti", minAmount: 20, maxAmount: 40 },
  { description: "Eni 54761", type: "expense", category: "Carburanti", minAmount: 15, maxAmount: 25 },
  { description: "Coil Srl-Ripacandida Ss Ofe", type: "expense", category: "Carburanti", minAmount: 20, maxAmount: 50 },
  { description: "Tamoil Km 31", type: "expense", category: "Carburanti", minAmount: 15, maxAmount: 35 },
  { description: "Conad Superstore", type: "expense", category: "Spesa e supermercati", minAmount: 30, maxAmount: 150 },
  { description: "Lidl", type: "expense", category: "Spesa e supermercati", minAmount: 20, maxAmount: 100 },
  { description: "Prelievo Sportello Banca Del Gruppo", type: "expense", category: "Prelievi", minAmount: 50, maxAmount: 500 },
  { description: "Area Di Servizio Monte Mila", type: "expense", category: "Carburanti", minAmount: 10, maxAmount: 30 },
  { description: "Q8 Easy Di Stazione Melfi", type: "expense", category: "Carburanti", minAmount: 15, maxAmount: 40 },
  { description: "Carburanti Orimini Srl", type: "expense", category: "Carburanti", minAmount: 25, maxAmount: 60 },
  { description: "Amzn Mktp It*2607l1t04", type: "expense", category: "Altre uscite", minAmount: 10, maxAmount: 50 },
  { description: "Amzn Mktp It*7y7e99r44", type: "expense", category: "Altre uscite", minAmount: 15, maxAmount: 40 },
  { description: "Amzn Mktp It*8k4x50h44", type: "expense", category: "Altre uscite", minAmount: 20, maxAmount: 80 },
  { description: "Amzn Mktp It*3ywr97ny4", type: "expense", category: "Altre uscite", minAmount: 25, maxAmount: 100 },
  { description: "Biglietto Treno Italo", type: "expense", category: "Trasporti e viaggi", minAmount: 30, maxAmount: 80, fixedAmounts: [35, 45, 55, 65, 75] },
  { description: "Trenitalia Spa", type: "expense", category: "Trasporti e viaggi", minAmount: 15, maxAmount: 60, fixedAmounts: [18, 25, 35, 45, 55] },
  { description: "Telepass", type: "expense", category: "Trasporti e viaggi", minAmount: 10, maxAmount: 30 },
  { description: "Bollo Auto Regione Basilicata", type: "expense", category: "Tasse e bolli", minAmount: 150, maxAmount: 350, fixedAmounts: [198, 220, 280] },
  { description: "Farmacia Comunale N.1", type: "expense", category: "Sanità", minAmount: 5, maxAmount: 30 },
  { description: "Farmacia San Michele", type: "expense", category: "Sanità", minAmount: 8, maxAmount: 45 },
];
